<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <ApplicationIcon>Assets/icon/tag-edit-blue.ico</ApplicationIcon>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <PackageVersion>0.13.1</PackageVersion>
        <!-- Compression slows launch but lowers build size.
        ReadyToRun speeds up launch, but increases build size.
        Base build size ~96MB, Compressed build size ~48MB, ReadyToRun+Compressed build size ~63MB
        Compression launch slowdown was not noticeable to me, ReadyToRun+Compression launches faster than base
        Going with ReadyToRun+Compression for faster launch and smaller, but not smallest, size
        PublishTrimmed is also an option to reduce size, but it breaks things and would need refactoring, mostly reflection and json (which might be reflection)
        -->
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
        <PublishReadyToRun>true</PublishReadyToRun>
    </PropertyGroup>
    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>
    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.2" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
        <PackageReference Include="Avalonia.Themes.Simple" Version="12.1.2" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
        <!--Condition below is needed to remove Avalonia Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
        <PackageReference Include="z440.atl.core" Version="7.17.0" />
    </ItemGroup>
</Project>
